spring:
  config:
    use-legacy-processing: true
  profiles:
    active: dev
  application:
    name: stockManagement
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/stockmanagement?createDatabaseIfNotExist=true&useSSL=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:

    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      poolName: Hikari
      connection-timeout: 180000
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 300000
      max-lifetime: 900000
      validation-timeout: 50000
      leak-detection-threshold: 180000
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    open-in-view: false
    database: MYSQL
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    web:
      pageable:
        default-page-size: 20

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: DEBUG

server:
  port: 8098
